/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#2e6769",
        "on-primary": "#ffffff",
        "primary-container": "#99d1d3",
        "on-primary-container": "#215b5d",
        "primary-fixed": "#b4edef",
        "primary-fixed-dim": "#98d0d2",
        "on-primary-fixed": "#002021",
        "on-primary-fixed-variant": "#104f51",
        "secondary": "#6d5a5b",
        "on-secondary": "#ffffff",
        "secondary-container": "#f7dcde",
        "on-secondary-container": "#735f61",
        "secondary-fixed": "#f7dcde",
        "secondary-fixed-dim": "#dac0c2",
        "on-secondary-fixed": "#26181a",
        "on-secondary-fixed-variant": "#544244",
        "tertiary": "#3b665f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a2d0c7",
        "on-tertiary-container": "#2f5a53",
        "tertiary-fixed": "#bdece2",
        "tertiary-fixed-dim": "#a2d0c6",
        "on-tertiary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#224e47",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f9f9f8",
        "on-background": "#1a1c1c",
        "surface": "#f9f9f8",
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#404849",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f3",
        "surface-container": "#eeeeed",
        "surface-container-high": "#e8e8e7",
        "surface-container-highest": "#e2e2e2",
        "surface-dim": "#dadad9",
        "surface-bright": "#f9f9f8",
        "surface-tint": "#2e6769",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1f0",
        "inverse-primary": "#98d0d2",
        "outline": "#707979",
        "outline-variant": "#bfc8c8",
        "white": "#FFFFFF",
        "slate-800": "#1E293B",
        "slate-500": "#64748B",
        "stone-50": "#fafaf9",
        "stone-100": "#f5f5f4",
        "teal-100": "#ccfbf1",
        "rose-100": "#ffe4e6",
      },
      fontFamily: {
        heebo: ["Heebo", "sans-serif"],
        assistant: ["Assistant", "sans-serif"],
      },
      fontSize: {
        "headline-3xl": ["30px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-3xl-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-xl": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "margin-desktop": "2.5rem",
        "card-padding": "1.5rem",
        gutter: "1rem",
        "stack-gap": "1rem",
      },
      boxShadow: {
        soft: "0px 12px 12px rgba(30,41,59,0.04)",
        nav: "0px -4px 12px rgba(30,41,59,0.04)",
      },
    },
  },
  plugins: [],
}
